apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-kubernetes-deployment

spec:
  replicas: 5
  selector:
    matchLabels:
      app: fastapi-kubernetes
  template:
    metadata:
      labels:
        app: fastapi-kubernetes
    spec:
      containers:
        - name: fastapi-kubernetes-app
          image: $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"