---
name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  IMAGE_NAME: ${{ github.event.repository.name }}
  REGION: ${{ secrets.REGION }}
  REPOSITORY: ${{ secrets.REPOSITORY }}

jobs:
  build-push-artifact-registry:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Verify Environment Variables
        run: echo Hola Mundo $IMAGE_NAME

      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
      
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .
      
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: v0.1.0
        run: |-
          docker tag $IMAGE_NAME:latest $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GIT_TAG
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GIT_TAG

  deploy-to-google-kubernetes-engine:
    needs: build-push-artifact-registry
    name: Deploy to Kubernetes Engine
    runs-on: ubuntu-latest
    steps:
      - name: Verify Environment Variables
        run: echo Hola mundo $IMAGE_NAME
